import type { PropsWithChildren } from 'react';
import { Document } from '@{workspace}/ui';

import '@{workspace}/ui/globals.css';
import { TRPCProvider } from '@/app/api/trpc/client';

export const metadata = {
  title: '{app}',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <Document>
      <TRPCProvider>{children}</TRPCProvider>
    </Document>
  );
}
